### ISSUE TITLE
warn.fail setting doesn't work

### ISSUE THREAD

**Issue by jerrygreen** [ReadyTalk/todolint#1]
The cli always return 0 status code, whether TODOs are found or not

**Comment by jahndis** [comment]
This was probably a result of not having a `warn.limit` config value set in your .todolintrc.json file. There was some faulty logic that was failing to exit with an error 1 status if `warn.limit` was set to either 0 or was not set at all even if `warn.fail` was set. This is fixed in 1.0.4.

Thanks for reporting!
